### ISSUE TITLE
It doesn't clear the bidirectional path residue

### ISSUE THREAD

**Issue by blueedgetechno** [dipeshpatil/algorithms-visualiser#1]
> generate maze
> Select Bi-Directional Search
> Perform search
> Clear maze

After doing this the traced path doesn't get erased.

**Comment by dipeshpatil** [comment]
Thankyou @blueedgetechno for raising this issue and Apologies for that, I recently updated it but forgot to update the clear function. I will rectify it soon!

**Comment by dipeshpatil** [comment]
@blueedgetechno Apologies for that, I recently updated it but forgot to update the clear function. I have rectified it and I am closing this issue! Thankyou for raising this issue.
